name: Deploy Nginx Application
on:
  push:
    branches: [ "main" ]
jobs:
  app-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        
      - name: Kind Cluster
        uses: helm/kind-action@v1.9.0

      - name: Deploy Sample Application
        run: |
          kubectl apply -f nginx-deployment.yaml

      - name: Check Deployed Resources Status
        run: |
          kubectl get all -o wide
          DEPLOYMENT_NAME=$(kubectl get deployment | grep nginx | awk '{print $1}')
          sleep 150s
          kubectl get pods
          kubectl get deployment
          kubectl wait --for=condition=Available deployment/$DEPLOYMENT_NAME --timeout=300s
